### ISSUE TITLE
some questions about flops and inference time

### ISSUE THREAD

**Issue by bendanzzc** [alibaba-mmai-research/TAdaConv#10]
Hi, thanks for your awesome work. 

when I use fvcore to count flops I find some ops are not supported.

when I count inference time between TAM and Tada R50. I found the inference time of Tada is much longer than TAM with the similar flops reported in the paper. Is it right?

by the way, the performence is truly  better than TAM

**Comment by huang-ziyuan** [comment]
Sorry for the delayed reply :). 

It is correct that the inference time of TAda2D is longer than TAM. Our analysis shows that the majority of the extra time is spent on the routing function. So the routing function could be further investigated if low latency is required.
