### ISSUE TITLE
TAdaConvNeXt-T

### ISSUE THREAD

**Issue by okojoalg** [alibaba-mmai-research/TAdaConv#11]
Are code and a pretrained weight of TAdaConvNeXt-T going to be public?

**Comment by leexinhao** [comment]
And I also curious about why the flops and parms of TAdaConvNeXt-T is one half of the ResNet50's, to my knowledge they should be similar.

![image](https://user-images.githubusercontent.com/48858574/216561648-8ca0df58-4202-4334-adfd-d3a1ca5ec7b1.png)

**Comment by huang-ziyuan** [comment]
> Are code and a pretrained weight of TAdaConvNeXt-T going to be public?

The code is made public now, but the weight for TAdaConvNeXt would not be released. But later we will release the pre-trained weights for TAdaConvNeXtV2 and TAdaFormer.

**Comment by huang-ziyuan** [comment]
> And I also curious about why the flops and parms of TAdaConvNeXt-T is one half of the ResNet50's, to my knowledge they should be similar.
> 
> ![image](https://user-images.githubusercontent.com/48858574/216561648-8ca0df58-4202-4334-adfd-d3a1ca5ec7b1.png)

The main reason is that TAdaConvNeXt-T downsamples the temporal resolution in the stem by 2.
