### ISSUE TITLE
Batch-wise and Temporal-wise modeling

### ISSUE THREAD

**Issue by hulianyuyy** [alibaba-mmai-research/TAdaConv#14]
I find that TAdaConv creates new convolutional weights for each independent batch and frame, is that right? If it is true, does the memory usage increase drastically, as convolutional weights are set independently for each batch and frame, which are not shared across time and batch?

**Comment by huang-ziyuan** [comment]
Hi, thanks for the comment! 
It is true that the memory will increase to a certain extend. However, it would be increased "drastically" since it is not required to store the gradient for the created convolution weights. :)
