### ISSUE TITLE
I am curious about why the flops and parms of TAdaConvNeXt-T is one half of the ResNet50's, to my knowledge they should be similar.

### ISSUE THREAD

**Issue by leexinhao** [alibaba-mmai-research/TAdaConv#15]
I am curious about why the flops and parms of TAdaConvNeXt-T is one half of the ResNet50's, to my knowledge they should be similar.

![image](https://user-images.githubusercontent.com/48858574/216561648-8ca0df58-4202-4334-adfd-d3a1ca5ec7b1.png)

_Originally posted by @leexinhao in https://github.com/alibaba-mmai-research/TAdaConv/issues/11#issuecomment-1415454364_
            
Could you give me the implement of TAdaConvNeXt？

**Comment by huang-ziyuan** [comment]
Sorry for the delayed reply. 

The reason for the reduced computation for TAdaConvNeXt is that we used a tublet embedding stem in TAdaConvNeXt model, which reduces the temporal resolution by a factor of 2 in the first downsample layer of ConvNeXt :). In contrast, the TAda2D stem employs only spatial convolutions with no temporal downsampling.

**Comment by leexinhao** [comment]
> Sorry for the delayed reply.
> 
> The reason for the reduced computation for TAdaConvNeXt is that we used a tublet embedding stem in TAdaConvNeXt model, which reduces the temporal resolution by a factor of 2 in the first downsample layer of ConvNeXt :). In contrast, the TAda2D stem employs only spatial convolutions with no temporal downsampling.

Thanks for your reply!
