### ISSUE TITLE
EPIC-KITCHENS Action Features

### ISSUE THREAD

**Issue by elias-work** [alibaba-mmai-research/TAdaConv#2]
Thank you so much for releasing this amazing work. I am really interested in this project and would like to try EPIC-KITCHENS action detection on custom video data with custom noun and verb sets. I'd like to try with EPIC-KITCHENS data first and I see feature zoo links aren't updated.

I'm wondering:
1) Would it be possible to briefly describe the format details of feature generation for custom data? 
2) Do you know when the EPIC-KITCHENS feature links will be uploaded/fixed?

**Comment by JackyTown** [comment]
我已经收到您的邮件，将尽快回复。

**Comment by huang-ziyuan** [comment]
Hi, thanks for the attention and sorry for the late reply. 

The features for epic-kitchens by TAda2D has been released in the feature zoo. You are welcome to try it out. The features by ViViT will be soon released as well.
