### ISSUE TITLE
Enquiry on the batch size when using 32-frames

### ISSUE THREAD

**Issue by PeiqinZhuang** [alibaba-mmai-research/TAdaConv#20]
Hi, may I ask about the batch size when taking 32 frames as input? Currently, configs are only applicable to 16-frame settings.

**Comment by huang-ziyuan** [comment]
Thanks for the attention. I am not sure which model are you referring to, but you can simply half the batch size when using 32 frames instead of 16 frames as the input.

**Comment by PeiqinZhuang** [comment]
Thank you for your answer. I will try to half the batch size.
