### ISSUE TITLE
Feedback on the issue of ema coefficient.

### ISSUE THREAD

**Issue by PeiqinZhuang** [alibaba-mmai-research/TAdaConv#22]
Hi, I just found that you do not turn on the ema mode in the released code. However, this is important for your training as mentioned in your paper. I just wonder if you have missed turning on the ema mode.

**Comment by huang-ziyuan** [comment]
Thanks for the feedback. Could you specify which model/config are you referring to?

**Comment by PeiqinZhuang** [comment]
Please refer to the following link. (https://github.com/alibaba-mmai-research/TAdaConv/blob/75b7839b37fc94d98d4fe5f2aff4b3df4e347dfb/configs/pool/base.yaml#L65) As mentioned, all configure files are based on the base configure file. However, the ema mode is turned off in the base configure file. If we want to execute the setting of tadaformer_b16_ssv2_16f, it is supposed to explicitly turn on the ema mode. BTW, the ema decay coefficient is different from what you reported in your work, e.g. 0.99996 v.s. 0.9996. Maybe you can check it later.

**Comment by huang-ziyuan** [comment]
Yes, if you wish to turn on EMA, you will have to manually enable ema and set the ema decay factor in your config file to run. We indeed used EMA during training TAdaFormer, but we actually observe negligible performance differences for the ema models and the original model. Therefore, turning on ema is not a must for training TAdaFormers.

**Comment by PeiqinZhuang** [comment]
As mentioned in your paper, turning on the ema mode may prevent the model from over-fitting problems. I am curious how important it is for training.

**Comment by huang-ziyuan** [comment]
It affects the top-1 accuracy by 0.2~0.4 for large models.
