### ISSUE TITLE
Use TAdaConv in Video Object Detection?

### ISSUE THREAD

**Issue by urbaneman** [alibaba-mmai-research/TAdaConv#8]
Thanks for your good job.
I want to use multi-frame information enhanced video small target detection.
**So, could I use the TAdaConv in Video Object Detection?**
If yes, what details should I be careful? How to fusion multi-frame feature, Concat, Add or ...? Do you have any advice? Thanks！

**Comment by huang-ziyuan** [comment]
Hi, thanks for your attention to our work.

You have raised an interesting question, which at present we do not have the answer for. The closest answer to your question would be our recent extension of TAdaConv to visual object tracking scenarios: [TCTrack](https://openaccess.thecvf.com/content/CVPR2022/papers/Cao_TCTrack_Temporal_Contexts_for_Aerial_Tracking_CVPR_2022_paper.pdf). The code for TCTrack is released [here](https://github.com/vision4robotics/TCTrack).

You are welcome to try exploring other structures for video object detection based on TAdaConv :).
