### ISSUE TITLE
How to use R(2+1)D with TAda?

### ISSUE THREAD

**Issue by sja9527** [alibaba-mmai-research/TAdaConv#9]
Can you show us the detail of using R(2+1)D with TAdaConv?

**Comment by huang-ziyuan** [comment]
Hi, we just updated the implementation for [TAdaConv3d](https://github.com/alibaba-mmai-research/TAdaConv/blob/main/models/module_zoo/ops/tadaconv.py). 

For using R(2+1)D with TAdaConv, 
1. follow the guideline in README.md to replace the 2d conv with TAdaConv2d
2. similarly, replace the original 1d conv with TAdaConv3d (with kernel set to [3,1,1]). 

For the implementation of the R(2+1)D in our paper, please refer to [r2plus1d_branch.py](https://github.com/alibaba-mmai-research/TAdaConv/blob/main/models/module_zoo/branches/r2plus1d_branch.py).
